repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.7.0-4
  hooks:
    - id: shfmt
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.20.0
  hooks:
    - id: stylua # or stylua-system / stylua-github
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.0
  hooks:
  - id: gitleaks
- repo: https://github.com/PrincetonUniversity/blocklint
  rev: v0.2.4
  hooks:
  - id: blocklint
