theme = "onedark"

[editor]
true-color = true
line-number = "relative"
soft-wrap.enable = true
middle-click-paste = true
scroll-lines = 5
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-format = true
auto-save = true
auto-info = true
bufferline = "multiple"
idle-timeout = 0
completion-trigger-len = 1

[editor.statusline]
left = ["spinner", "spacer", "diagnostics", "spacer", "file-name"]
center = []
right = ["version-control", "spacer", "position"]
separator = "│"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.select]
minus = "trim_selections"
"`" = "switch_case"
r = "replace_with_yanked"

[keys.normal]
minus = "trim_selections"
"`" = "switch_case"
";" = "flip_selections"
"esc" = ["collapse_selection", "keep_primary_selection"]
d = "delete_selection"
c = "change_selection"
D = "delete_selection_noyank"
C = "change_selection_noyank"
M = "join_selections"
J = "copy_selection_on_next_line"
K = "copy_selection_on_prev_line"
r = "replace_with_yanked"
Y = ":clipboard-yank-join"
C-b = "increment"
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-j = "half_page_down"
A-k = "half_page_up"
"A-." = "goto_next_buffer"
"A-," = "goto_previous_buffer"

"!" = [":register-mark", "1"]
"1" = [":goto-mark", "1"]
"@" = [":register-mark", "2"]
"2" = [":goto-mark", "2"]
"#" = [":register-mark", "3"]
"3" = [":goto-mark", "3"]
"$" = [":register-mark", "4"]
"4" = [":goto-mark", "4"]

[keys.normal."space".a]
t = "signature_help"
r = "rename_symbol"
k = "hover"
f = ":format"
a = "code_action"


[keys.normal."space".f]
"f" = "file_picker"
"r" = ":reload-all"
"w" = ":wa"
"c" = ":bc"
"C" = ":bca"

[keys.normal."backspace"]
s = "symbol_picker"
"j" = "jumplist_picker"
"a" = "code_action"

[keys.normal."backspace".m]
p = [
  ":open ~/Documents/projects/helix-macros/python.hxm",
  "extend_to_line_bounds",
]
r = [
  ":open ~/Documents/projects/helix-macros/rust.hxm",
  "extend_to_line_bounds",
]

[keys.normal."backspace".f]
"r" = ":reload-all"
"f" = "file_picker"
"w" = ":wa"
"c" = ":bc"
"q" = ":bc"

[keys.normal."backspace".c]
c = ":config-open"
l = ":open ~/.config/helix/languages.toml"
r = ":config-reload"
