theme = "onedark"
[editor]
true-color = true
line-number = "relative"
soft-wrap.enable = true
shell = ["zsh", "-c"]
scrolloff = 8
middle-click-paste = true
scroll-lines = 5
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-format = true
auto-save = true
auto-info = true
bufferline = "multiple"
idle-timeout = 0
completion-trigger-len = 1

[editor.statusline]
left = ["spinner", "spacer", "diagnostics", "spacer", "file-name"]
center = []
right = ["version-control", "spacer", "position"]
separator = "│"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.select]
minus = "trim_selections"
"`" = "switch_case"
r = "replace_with_yanked"

[keys.normal]
minus = "trim_selections"
"`" = "switch_case"
";" = "flip_selections"
"esc" = ["collapse_selection", "keep_primary_selection"]
D = "delete_selection_noyank"
C = "change_selection_noyank"
M = "join_selections"
J = "copy_selection_on_next_line"
K = "copy_selection_on_prev_line"
r = "replace_with_yanked"
Y = ":clipboard-yank-join"
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]


[keys.normal."space"]
t = "signature_help"
"r" = ":reload-all"
"w" = ":wa"
"c" = ":bc"

[keys.normal."space".f]
"f" = "file_picker"
"r" = ":reload-all"
"w" = ":wa"
"c" = ":bc"
"q" = ":bc"

[keys.normal."backspace"]
s = "symbol_picker"
"t" = [
  ":toggle file-picker.parents",
  ":toggle file-picker.hidden",
  "file_picker",
  ":toggle file-picker-.parents",
  ":toggle file-picker.hidden",
]
"j" = "jumplist_picker"
"a" = "code_action"

[keys.normal."space".l]
r = ":lsp-restart"

[keys.normal."backspace".f]
"r" = ":reload-all"
"f" = "file_picker"
"w" = ":wa"
"c" = ":bc"
"q" = ":bc"

[keys.normal."]"]
f = ["goto_next_function", "flip_selections", "align_view_top"]

[keys.normal."backspace".c]
c = ":config-open"
l = ":open ~/.config/helix/languages.toml"
r = ":config-reload"
