[[language]]
name = "python"
roots = ["pyproject.toml"]
auto-format = true
language-servers = [{ name = 'ruff' }, { name = 'pyright' }]
formatter = { command = "ruff", args = ["format", "--check", "-"] }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua" }
language-servers = [{ name = "lua-language-server" }]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ['-'] }
language-servers = [{ name = "bash-language-server" }]


[[language]]
name = "markdown"
auto-format = true
language-servers = [{ name = "marksman" }]

[[language]]
name = "yaml"
auto-format = true
language-servers = [{ name = "yaml-language-server" }]

[[language]]
name = "hcl"
auto-format = true
language-servers = [{ name = "terraform-ls" }]

[[language]]
name = "dockerfile"
auto-format = true
language-servers = [{ name = "docker-langserver" }]

[[language]]
name = "svelte"
auto-format = true
language-servers = [{ name = "svelteserver" }]

[[language]]
name = "jinja"
auto-format = true
file-types = [".html"]
language-servers = [{ name = "jinja-lsp" }]
formatter = { command = "djlint", args = ['--reformat', 'templates'] }

[[language]]
name = "julia"
auto-format = true
language-servers = [{ name = "julia" }]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
language-servers = [{ name = "taplo" }]

[lanugage-server.jinja-lsp]
command = "jinja-lsp"
config = { templates = "./templates" }

[lanugage-server.svelteserver]
command = "svelteserver"

[lanugage-server.docker-langserver]
command = "docker-langserver"

[lanugage-server.yaml-language-server]
command = "yaml-language-server"

[lanugage-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[lanugage-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
