[misc]
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["pip3", "pipx", "conda", "mamba", "julia", "juliaup", "vim"]
# neovim update causes conficts with lazy lockfile during git pull so I'll do that manually
# the others I need on system for work, but don't really use and don't want to spend time updating


# Ignore failures for these steps
no_retry = true

# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
pre_sudo = true

display_time = true
cleanup      = false

[composer]
self_update = true

[git]
max_concurrency = 5
pull_predefined = true

repos = ["~/projects/*/*"]


[windows]
# Manually select Windows updates
accept_all_updates           = true
open_remotes_in_new_terminal = true
wsl_update_pre_release       = true
wsl_update_use_web_download  = true

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop or Cargo
self_rename = true

[firmware]
upgrade = true
