matches:
  - trigger: ";eur"
    replace: €
  - trigger: ";shrug"
    replace: ¯\_(ツ)_/¯
  - trigger: ";flipt"
    replace: (╯°□°)╯︵ ┻━┻
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ";week"
    replace: "{{year}} week {{week}}"
    vars:
      - name: year
        type: date
        params:
          format: "%Y"
      - name: week
        type: date
        params:
          format: "%W"
  - trigger: ";isodate"
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "deg C"
    replace: "°C"
  - trigger: "helene"
    replace: "Hélène"
  - trigger: "Helene"
    replace: "Hélène"
  - trigger: umit
    replace: Ümit
