matches:
  - trigger: ";eur"
    replace: €
  - trigger: ";shrug"
    replace: ¯\_(ツ)_/¯
  - trigger: ";flipt"
    replace: (╯°□°)╯︵ ┻━┻
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ";isodate"
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ";eyes"
    replace: 👀
  - trigger: ";music"
    replace: 🎵
  - trigger: ";small"
    replace: 🤏
  - trigger: ";think"
    replace: 🤔
  - trigger: ";imp"
    replace: 😈
  - trigger: ";sparkle"
    replace: ✨
  - trigger: ";skull"
    replace: 💀
  - trigger: ";sweat"
    replace: 😅
  - trigger: ";scream"
    replace: 😱
  - trigger: "deg C"
    replace: "°C"
  - trigger: "helene"
    replace: "Hélène"
  - trigger: "Helene"
    replace: "Hélène"
  - trigger: ;hmt
    replace: HydroMT
  - trigger: ;rd
    replace: raison d'être
  - trigger: umit
    replace: Ümit
  - trigger: ;dh
    replace: ":dragon_heart:"
  # - trigger: nj
  #   replace: ñ
  - trigger: "''e"
    replace: é
  - trigger: "''i"
    replace: í
  - trigger: "''a"
    replace: á
  - trigger: "''o"
    replace: ó
  - trigger: "''u"
    replace: ú
