theme = "onedark"

[editor]
true-color             = true
line-number            = "relative"
soft-wrap.enable       = true
middle-click-paste     = true
scroll-lines           = 8
cursorline             = true
gutters                = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-format            = true
auto-save              = true
auto-info              = true
bufferline             = "multiple"
idle-timeout           = 0
completion-trigger-len = 1

# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
other-lines = "error"


[editor.statusline]
left      = ["spinner", "spacer", "diagnostics", "spacer", "file-name"]
center    = []
right     = ["version-control", "spacer", "position"]
separator = "│"

[editor.lsp]
enable                             = true
display-messages                   = true
auto-signature-help                = true
display-inlay-hints                = true
display-signature-help-docs        = true
snippets                           = true
goto-reference-include-declaration = true

[editor.indent-guides]
render      = true
character   = "┆"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.select]
minus = "trim_selections"
r     = "replace_with_yanked"
Y     = ":clipboard-yank-join"
A-j   = "half_page_down"
A-k   = "half_page_up"
"A-." = "goto_next_buffer"
"A-," = "goto_previous_buffer"
"C-n" = "goto_next_tabstop"
"C-p" = "goto_prev_tabstop"


[keys.normal]
minus = "trim_selections"
";"   = "flip_selections"
"esc" = ["collapse_selection", "keep_primary_selection"]
d     = "delete_selection"
c     = "change_selection"
D     = "delete_selection_noyank"
C     = "change_selection_noyank"
M     = "join_selections"
J     = "copy_selection_on_next_line"
K     = "copy_selection_on_prev_line"
r     = "replace_with_yanked"
R     = "replace_selections_with_clipboard"
Y     = ":clipboard-yank-join"
A-j   = "half_page_down"
A-k   = "half_page_up"
"A-." = "goto_next_buffer"
"A-," = "goto_previous_buffer"


# project namespace
[keys.normal."space".p]
label = "Project"
"/"   = "global_search"
s     = "workspace_symbol_picker"
g     = "changed_file_picker"
f     = "file_picker"
D     = "workspace_diagnostics_picker"

# Language namespace
[keys.normal."space".l]
label = "LSP"
r     = "rename_symbol"
d     = "hover"
h     = "select_references_to_symbol_under_cursor"
a     = "code_action"
c     = "completion"

# lsp/comment
[keys.normal."space".l."/"]
label = "Comments"
c     = "toggle_comments"
l     = "toggle_line_comments"
b     = "toggle_block_comments"


# lsp/signature
[keys.normal."space".l.f]
label = "Function"
h     = "signature_help"
i     = "add_function_parameter"
p     = "goto_prev_parameter"
n     = "goto_next_parameter"


# file namespace
[keys.normal."space".f]
label = "File"
"/"   = "search"
s     = "symbol_picker"
d     = "diagnostics_picker"
r     = { label = "Reaload all files", command = ":reload-all" }
w     = { label = "Write all files", command = ":wa" }
c     = { label = "Close current buffer", command = ":bc" }
f     = { label = "Format Document", command = ":format" }

# config namespace
[keys.normal."space".c]
label = "Config"
c     = { label = "Open Config", command = ":config-open" }
l     = { label = "Open Language Config", command = ":open ~/.config/helix/languages.toml" }
r     = { label = "Reload Config", command = ":config-reload" }

# marks namespace
[keys.normal."space".m]
label = "Marks"

[keys.normal."space".m.g]
label = "Goto"
"1"   = ":goto-mark 1"
"2"   = ":goto-mark 2"
"3"   = ":goto-mark 3"
"4"   = ":goto-mark 4"

[keys.normal."space".m.s]
label = "Set"
"1"   = ":register-mark 1"
"2"   = ":register-mark 2"
"3"   = ":register-mark 3"
"4"   = ":register-mark 4"

[keys.normal."space".g]
label = "Git"
s     = { label = "Status", command = ":sh git status" }
p     = { label = "pull", command = ":sh git pull" }
u     = { label = "undo change under cursor", command = ":reset-diff-change" }

[keys.normal."space".t]
label = "Test"

[keys.normal."space".t.p]
label = "Python"

[keys.normal."space".t.r]
label = "Rust"

[keys.normal."space".d]
label = "Debug"
c     = "dap_continue"
r     = "dap_restart"
t     = "dap_terminate"
v     = "dap_variables"
n     = "dap_next"
s     = "dap_step_in"
o     = "dap_step_out"
b     = "dap_toggle_breakpoint"
l     = "dap_launch"

# nops to clean up menus
[keys.normal."space"]
"G"   = "no_op"
"'"   = "no_op"
"P"   = "no_op"
"y"   = "no_op"
"Y"   = "no_op"
"D"   = "no_op"
"h"   = "no_op"
"s"   = "no_op"
"i"   = "no_op"
"S"   = "no_op"
"r"   = "no_op"
"b"   = "no_op"
"j"   = "no_op"
"C"   = "no_op"
"F"   = "no_op"
"R"   = "no_op"
"k"   = "no_op"
"A-c" = "no_op"
"/"   = "no_op"
